### PR TITLE
Code for converting tabs to spaces in filledText

### PR DESCRIPTION
**Pull request by pratikju**
In case we need to show the indented output on the console(say, JSON response), added code will convert tabs to spaces while rendering.

### CODE REVIEW

**Comment by chrisdone** [comment]
Works for me.

**Comment by pratikju** [comment]
While scrolling up, when I am double clicking on the console to copy items, it scrolls down to the bottom.
Is this an intended functionality ??

**Comment by chrisdone** [comment]
Yep. Terminals do that.

**Comment by chrisdone** [comment]
There might be an option about scrolling though. Let me check.

**Pull request merged**
